### ISSUE TITLE
ng-packager build error - Cannot read property 'type' of null

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit.envs#39]
Part of the process of stabilizing the experimental implementation of the Angular Bit compiler I'm running tests on well-known OSS projects that maintain Angular components.

When trying to build [ngx-bootstrap](https://github.com/valor-software/ngx-bootstrap), I'm getting an error when building these components:

- src/accordion
- src/carousel
- src/progressbar
- src/tabs
- src/alert
- src/chronos
- src/datepicker
- src/pagination
- src/rating
- src/timepicker
- src/typeahead
- src/popover
- src/tooltip
- src/sortable

The same general error occurs on all components (Cannot read property 'type' of null):

```
› bd build sortable

 directory /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-46721

Error in packaging component!
 { Error: Command failed: node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-46721/components/sortable/ng-package.json

BUILD ERROR
Cannot read property 'type' of null

Building Angular Package
Building entry point '@bit/sortable'
Compiling TypeScript sources through ngc

    at makeError (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 111,
  stdout: 'Building Angular Package\nBuilding entry point \'@bit/sortable\'\nCompiling TypeScript sources through ngc\n',
  stderr: '\nBUILD ERROR\nCannot read property \'type\' of null\n',
  failed: true,
  signal: null,
  cmd: 'node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-46721/components/sortable/ng-package.json',
  timedOut: false,
  killed: false }
error: bit failed to build sortable with the following exception:
Command failed: node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-46721/components/sortable/ng-package.json

BUILD ERROR
Cannot read property 'type' of null

Building Angular Package
Building entry point '@bit/sortable'
Compiling TypeScript sources through ngc

Error: Command failed: node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-46721/components/sortable/ng-package.json

BUILD ERROR
Cannot read property 'type' of null

Building Angular Package
Building entry point '@bit/sortable'
Compiling TypeScript sources through ngc

    at makeError (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Additionally, on this component I'm getting a different error (Property 'pipe' does not exist on type 'EventEmitter<boolean>'.):

- src/dropdown

```
› bd build dropdown

 directory /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632

Error in packaging component!
 { Error: Command failed: node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/ng-package.json

BUILD ERROR
../../../var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/src/dropdown/bs-dropdown.directive.ts(198,10): error TS2339: Property 'pipe' does not exist on type 'EventEmitter<boolean>'.


Building Angular Package
Building entry point '@bit/dropdown'
Compiling TypeScript sources through ngc

    at makeError (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 111,
  stdout: 'Building Angular Package\nBuilding entry point \'@bit/dropdown\'\nCompiling TypeScript sources through ngc\n',
  stderr: '\nBUILD ERROR\n../../../var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/src/dropdown/bs-dropdown.directive.ts(198,10): error TS2339: Property \'pipe\' does not exist on type \'EventEmitter<boolean>\'.\n\n',
  failed: true,
  signal: null,
  cmd: 'node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/ng-package.json',
  timedOut: false,
  killed: false }
error: bit failed to build dropdown with the following exception:
Command failed: node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/ng-package.json

BUILD ERROR
../../../var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/src/dropdown/bs-dropdown.directive.ts(198,10): error TS2339: Property 'pipe' does not exist on type 'EventEmitter<boolean>'.


Building Angular Package
Building entry point '@bit/dropdown'
Compiling TypeScript sources through ngc

Error: Command failed: node /private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/ng-packagr/cli/main.js -p /var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/ng-package.json

BUILD ERROR
../../../var/folders/sz/r_xm8b7d5jd2sw361yqv7tn80000gn/T/capsule-17632/components/dropdown/src/dropdown/bs-dropdown.directive.ts(198,10): error TS2339: Property 'pipe' does not exist on type 'EventEmitter<boolean>'.


Building Angular Package
Building entry point '@bit/dropdown'
Compiling TypeScript sources through ngc

    at makeError (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/private/tmp/ngx-bootstrap/.git/bit/components/ng-packagr/qballer.ng-test/0.0.6/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

error TS2339: Property 'pipe' does not exist on type 'EventEmitter<boolean>'.

The compiler work for these components:

- src/buttons
- src/utils
- src/collapse
- src/locale

The project's build process is working correctly (npm run build).

**Comment by itaymendel** [comment]
Update - getting the same error for this project - https://github.com/NG-ZORRO/ng-zorro-antd
When building `components/card`.

**Comment by qballer** [comment]
Ok it seems that ngx-bootstrap mostly works. I'm currently trying to resolve primeng which proves to be a real issue.

**Comment by GiladShoham** [comment]
@qballer That's the same error I got on few component in ngx-bootstrap. Components which worked from your machine. (Maybe it's something with the linux / mac diffs)

**Comment by qballer** [comment]
it isn't @GiladShoham , the same issues are observed by @Tallyb, she is running a linux machine. I'm making some fundamental changes due to primeng structure. When those are done I will revisit ngx-bootstrap

**Comment by GiladShoham** [comment]
@qballer Great, let me know if you want me to test it again with an updated version.
